### ISSUE TITLE
Нужен рефакторинг

### ISSUE THREAD

**Issue by tshemsedinov** [zemark-prog/Crosses-Crosses-Bot#1]
- [x] Посмотри лекции по рефакторингу, в этом коде куча всего:
- [x] Глубокая вложенность циклов
- [x] Глубокая вложенность ИФ-ов
- [x] Красивые столбики
- [x] Нужно делать промежуточные переменные, а не длинные выражения
- [x] Некоторые функции нужно разделить на более мелкие
- [x] Код плохо читается

**Comment by zemark-prog** [comment]
Все исправил
